import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

const sidebars: SidebarsConfig = {
  docs: [
    // Top-level standalone pages
    'hello',
    'getting_started',
    'short_doc',
    // Other section: default cards
    {
      type: 'category', // ❗ Change from 'autogenerated' to 'category'
      label: 'Full Documentation', // You must provide a label for the dropdown.
      description: 'Class & APIs Documentation',
      link: {
        type: 'generated-index', // ❗ Use a generated index link.
      },
      items: [
        {
          type: 'autogenerated', // ❗ Nest the 'autogenerated' type inside the 'items' array.
          dirName: 'full_doc',
        },
      ],
    },

    // Cookbook: custom list
    {
      type: 'category',
      label: 'The refx Cookbook',
      link: {
        type: 'doc',
        id: 'cookbook/index',
      },
      // ❗ Items MUST be listed here for the sidebar to display them.
      items: [
        'cookbook/imu_comp',
        'cookbook/relative_to_global',
      ],
    },
  ],
};

export default sidebars;
